### ISSUE TITLE
Stripe Production checklist

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-cli#49]
- [ ] Create stripe plans, subscriptions, products in prod account

- [ ] Add bank account to stripe

- [ ]  register webhook url with events

- [ ] Add stripe env variables
